dataset: "ESD_HED"

path:
  corpus_path: "/scratch/s5858895/Summary-Hierarchical-ED/implementation/Dataset/Emotion Speech Dataset"  # 音频源路径（.wav 和 .lab 文件）
  lexicon_path: "lexicon/librispeech-lexicon.txt"    # 英文发音词典路径
  raw_path: "/scratch/s5858895/Summary-Hierarchical-ED/implementation/Dataset/Emotion Speech Dataset"      # 父目录（和 corpus_path 保持一致）
  preprocessed_path: "/scratch/s5858895/FastSpeech2/preprocessed_data/ESD_HED"    # FastSpeech2 预处理输出路径

preprocessing:
  val_size: 512   # 验证集样本数量
  text:
    text_cleaners: ["english_cleaners"]   # 英文文本清洗器
    language: "en"                        # 英语
  audio:
    sampling_rate: 22050                  # ESD数据集采样率是16kHz
    max_wav_value: 32768.0                 # wav数值范围
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000                         # HiFi-GAN用8000，MelGAN用null
  pitch:
    feature: "phoneme_level"
    normalization: true
  energy:
    feature: "phoneme_level"
    normalization: true
